// Merged package: Proto.Design.FieldObjectSceneData

package Proto.Design.FieldObjectSceneData;





// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1.proto
message FieldObjectSceneData1 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData10.proto
message FieldObjectSceneData10 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData10001.proto
message FieldObjectSceneData10001 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData10004.proto
message FieldObjectSceneData10004 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData10006.proto
message FieldObjectSceneData10006 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1001.proto
message FieldObjectSceneData1001 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1002.proto
message FieldObjectSceneData1002 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1003.proto
message FieldObjectSceneData1003 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1004.proto
message FieldObjectSceneData1004 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1005.proto
message FieldObjectSceneData1005 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1006.proto
message FieldObjectSceneData1006 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1007.proto
message FieldObjectSceneData1007 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11.proto
message FieldObjectSceneData11 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11001.proto
message FieldObjectSceneData11001 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11002.proto
message FieldObjectSceneData11002 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11003.proto
message FieldObjectSceneData11003 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11004.proto
message FieldObjectSceneData11004 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11005.proto
message FieldObjectSceneData11005 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11006.proto
message FieldObjectSceneData11006 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11007.proto
message FieldObjectSceneData11007 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12.proto
message FieldObjectSceneData12 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12001.proto
message FieldObjectSceneData12001 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12002.proto
message FieldObjectSceneData12002 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12003.proto
message FieldObjectSceneData12003 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12004.proto
message FieldObjectSceneData12004 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12005.proto
message FieldObjectSceneData12005 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12006.proto
message FieldObjectSceneData12006 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12007.proto
message FieldObjectSceneData12007 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData13.proto
message FieldObjectSceneData13 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData14.proto
message FieldObjectSceneData14 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData15.proto
message FieldObjectSceneData15 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData16.proto
message FieldObjectSceneData16 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData17.proto
message FieldObjectSceneData17 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData18.proto
message FieldObjectSceneData18 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2.proto
message FieldObjectSceneData2 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2001.proto
message FieldObjectSceneData2001 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2002.proto
message FieldObjectSceneData2002 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2003.proto
message FieldObjectSceneData2003 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2004.proto
message FieldObjectSceneData2004 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2005.proto
message FieldObjectSceneData2005 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2006.proto
message FieldObjectSceneData2006 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2007.proto
message FieldObjectSceneData2007 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3.proto
message FieldObjectSceneData3 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3001.proto
message FieldObjectSceneData3001 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3002.proto
message FieldObjectSceneData3002 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3003.proto
message FieldObjectSceneData3003 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3004.proto
message FieldObjectSceneData3004 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3005.proto
message FieldObjectSceneData3005 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3006.proto
message FieldObjectSceneData3006 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3007.proto
message FieldObjectSceneData3007 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData4.proto
message FieldObjectSceneData4 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData5.proto
message FieldObjectSceneData5 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData6.proto
message FieldObjectSceneData6 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData7.proto
message FieldObjectSceneData7 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData8.proto
message FieldObjectSceneData8 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}

// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData9.proto
message FieldObjectSceneData9 {
  optional int32 id = 1;
  optional string objectName = 2;
  optional int32 objectType = 3;
  optional double positionX = 4;
  optional double positionY = 5;
  optional double positionZ = 6;
  optional string sceneName = 7;
  optional int32 tableId = 8;
}
