use actix_web::middleware::from_fn;
use actix_web::{App, HttpServer};
use common::{CERT_FILE_PATH, GAME_SERVER_ADDRESS, KEY_FILE_PATH, init_tracing};
use database::{DatabaseSettings, connect_to, run_migrations};
use middleware::{auth::auth_middleware, logger::Logger};
use std::path::PathBuf;
use tracing::{error, info};

use actix_web::web::Data;
use rustls::{
    ServerConfig,
    pki_types::{CertificateDer, PrivateKeyDer},
};
use rustls_pemfile::{certs, pkcs8_private_keys, rsa_private_keys};
use std::{fs::File, io::BufReader};

mod middleware;
mod routes;

#[actix_web::main]
async fn main() -> anyhow::Result<()> {
    {
        init_tracing();

        let data_path = get_data_path()?;
        info!("Found data path: {}", data_path.display());

        let settings = DatabaseSettings::default();

        let db = connect_to(&settings).await.map_err(|e| {
            eprintln!("Database connection error: {:?}", e);
            std::io::Error::new(std::io::ErrorKind::Other, e)
        })?;

        run_migrations(&db).await.map_err(|e| {
            eprintln!("Migration error: {:?}", e);
            std::io::Error::new(std::io::ErrorKind::Other, e)
        })?;

        //excel db loader
        info!("Loading game data...");
        data::exceldb::init(data_path.to_str().unwrap()).map_err(|e| {
            error!("Failed to load game data: {:#}", e);
            e
        })?;
        info!("Game data loaded");

        use anyhow::Context;
        info!("Opening cert file at: {:?}", &*CERT_FILE_PATH);
        let cert_file = &mut BufReader::new(
            File::open(&*CERT_FILE_PATH)
                .with_context(|| format!("opening cert file {:?}", &*CERT_FILE_PATH))?,
        );
        let cert_chain: Vec<CertificateDer> = certs(cert_file).collect::<Result<Vec<_>, _>>()?;

        info!("Opening key file at: {:?}", &*KEY_FILE_PATH);
        let mut keys: Vec<PrivateKeyDer> = {
            let mut key_reader = BufReader::new(
                File::open(&*KEY_FILE_PATH)
                    .with_context(|| format!("opening key file {:?}", &*KEY_FILE_PATH))?,
            );
            let pkcs8 = pkcs8_private_keys(&mut key_reader)
                .collect::<Result<Vec<_>, _>>()?
                .into_iter()
                .map(PrivateKeyDer::Pkcs8)
                .collect::<Vec<_>>();

            if !pkcs8.is_empty() {
                pkcs8
            } else {
                let mut key_reader = BufReader::new(File::open(&*KEY_FILE_PATH)?);
                rsa_private_keys(&mut key_reader)
                    .collect::<Result<Vec<_>, _>>()?
                    .into_iter()
                    .map(PrivateKeyDer::Pkcs1)
                    .collect()
            }
        };

        let mut tls_config = ServerConfig::builder()
            .with_no_client_auth()
            .with_single_cert(cert_chain, keys.remove(0))?;
        tls_config.alpn_protocols = vec![b"h2".to_vec(), b"http/1.1".to_vec()];

        let app_factory = move || {
            App::new()
                .wrap(from_fn(Logger))
                .wrap(from_fn(auth_middleware))
                .app_data(Data::new(db.clone()))
                // Basic routes
                .service(routes::basic::notice_info::notice_info_handler)
                .service(routes::basic::maintenace_info::maintenance_info_handler)
                .service(routes::basic::server_info::server_info_handler)
                .service(routes::basic::state_check_info_json::state_check_info_handle)
                // User routes
                .service(routes::user::login_user::login_user_handler)
                // Default routes
                .service(routes::default::balance_version_check::balance_check_version_handler)
                // Batch route (main batch endpoint)
                .service(routes::default::batch::batch::batch_request_handler)
                .service(routes::default::batch::batch::mission_info_handler)
                .service(routes::default::batch::batch::char_info_handler)
                .service(routes::default::batch::batch::recipe_info_handler)
                .service(routes::game::login::login_event::login_event_handler)
                .service(routes::game::schedule::schedule_info::schedule_info_handler)
                .service(routes::game::event::event_mission_info::event_mission_info_handler)
                .service(routes::game::event::event_reward_history::event_reward_history_handler)
                .service(routes::game::pack::pack_event_story_info::pack_event_story_info_handler)
                .service(routes::game::pack::pack_event_battle_info::pack_event_battle_info_handler)
                .service(routes::game::pictorial::pictorial_book_info::pictorial_book_info_handler)
                .service(routes::game::attendance::attendance::attendance_info_handler)
                .service(routes::game::all::all_char_refresh::all_char_refresh_info_handler)
                .service(routes::game::save::save_total_battle_power::save_total_battle_power_handler)
                .service(routes::game::charge::charge_cost_info::charge_cost_info_handler)
                .service(routes::basic::localization::localization_handler)
                .service(routes::basic::loki::loki_handler)
                .service(routes::game::equip::equip_info::equip_info_handler)
                .service(routes::game::pack::pack_preview_info::pack_preview_info_handler)
                .service(routes::game::monster::monster_info::monster_info_handler)
                .service(routes::game::today::today_quest_info::today_quest_info_handler)
                .service(routes::game::waypoint::waypoint_info::waypoint_info_handler)
                .service(routes::game::field::field_deck_info::field_deck_info_handler)
                .service(routes::game::hunting::hunting_ground_info_list::hunting_ground_info_list_handler)
                .service(routes::game::hunting::hunting_ground_info::hunting_ground_info_handler)
                .service(routes::game::tutorial::tutorial_clear::tutorial_clear_handler)
                .service(routes::game::notice::notice_detail_info::notice_detail_info_handler)
                .service(routes::game::save::save_user_position::save_user_position_handler)
                .service(routes::game::waypoint::waypoint_save::waypoint_save_handler)
                .service(routes::game::server::server_now_time::server_now_time_handler)
                .service(routes::game::field::field_object_reward::field_object_reward_handler)
                .service(routes::game::active::active_map::active_map_handler)
                .service(routes::game::quest::quest_update::quest_update_handler)
                .service(routes::game::quest::quest_clear::quest_clear_handler)
                .service(routes::game::achievement::achievement_clear::achievement_clear_handler)
                .service(routes::game::achievement::achievement_info::achievement_info_handler)
                .service(routes::game::achievement::achievement_update::achievement_update_handler)
                .service(routes::game::alchemy::alchemy::alchemy_handler)
                .service(routes::game::alchemy::alchemy_batch::alchemy_batch_handler)
                .service(routes::game::attendance::attendance_info::attendance_info_handler)
                .service(routes::game::battle::battle_end::battle_end_handler)
                .service(routes::game::battle::battle_end_test::battle_end_test_handler)
                .service(routes::game::battle::battle_enter::battle_enter_handler)
                .service(routes::game::battle::battle_exit::battle_exit_handler)
                .service(routes::game::battle::battle_give_up::battle_give_up_handler)
                .service(routes::game::battle::battle_retry::battle_retry_handler)
                .service(routes::game::battle::battle_retry_previous_turn::battle_retry_previous_turn_handler)
                .service(routes::game::battle::battle_start::battle_start_handler)
                .service(routes::game::battle::battle_verify_state::battle_verify_state_handler)
                .service(routes::game::cafeteria::cafeteria_cumulative_reward::cafeteria_cumulative_reward_handler)
                .service(routes::game::cafeteria::cafeteria_daily_connection_costume_refresh::cafeteria_daily_connection_costume_refresh_handler)
                .service(routes::game::cafeteria::cafeteria_event_npc_interaction_reward::cafeteria_event_npc_interaction_reward_handler)
                .service(routes::game::cafeteria::cafeteria_info::cafeteria_info_handler)
                .service(routes::game::cafeteria::cafeteria_introduction_story_reward::cafeteria_introduction_story_reward_handler)
                .service(routes::game::cafeteria::cafeteria_level_up::cafeteria_level_up_handler)
                .service(routes::game::cafeteria::cafeteria_manage_item_add::cafeteria_manage_item_add_handler)
                .service(routes::game::cafeteria::cafeteria_rare_npc_interaction_reward::cafeteria_rare_npc_interaction_reward_handler)
                .service(routes::game::cafeteria::cafeteria_regular_costume_interaction_all_reward::cafeteria_regular_costume_interaction_all_reward_handler)
                .service(routes::game::cafeteria::cafeteria_regular_costume_interaction_reward::cafeteria_regular_costume_interaction_reward_handler)
                .service(routes::game::cafeteria::cafeteria_regular_costume_note_all_reward::cafeteria_regular_costume_note_all_reward_handler)
                .service(routes::game::cafeteria::cafeteria_regular_costume_note_info::cafeteria_regular_costume_note_info_handler)
                .service(routes::game::cafeteria::cafeteria_regular_costume_note_reward::cafeteria_regular_costume_note_reward_handler)
                .service(routes::game::cafeteria::cafeteria_reward_receipt_time_update_using_cheat::cafeteria_reward_receipt_time_update_using_cheat_handler)
                .service(routes::game::cafeteria::cafeteria_spawn_reset::cafeteria_spawn_reset_handler)
                .service(routes::game::cafeteria::cafeteria_spawn_reset_cheat::cafeteria_spawn_reset_cheat_handler)
                .service(routes::game::cancel::cancel_leave_user::cancel_leave_user_handler)
                .service(routes::game::cash::cash_mail_info::cash_mail_info_handler)
                .service(routes::game::cash::cash_shop_buy::cash_shop_buy_handler)
                .service(routes::game::cash::cash_shop_info::cash_shop_info_handler)
                .service(routes::game::cash::cash_shop_purchase_count_info::cash_shop_purchase_count_info_handler)
                .service(routes::game::char::char_all_revival::char_all_revival_handler)
                .service(routes::game::char::char_auto_revive_set::char_auto_revive_set_handler)
                .service(routes::game::char::char_awake_active::char_awake_active_handler)
                .service(routes::game::char::char_awake_info::char_awake_info_handler)
                .service(routes::game::char::char_class_up::char_class_up_handler)
                .service(routes::game::char::char_expiry::char_expiry_handler)
                .service(routes::game::char::char_growth::char_growth_handler)
                .service(routes::game::char::char_healing::char_healing_handler)
                .service(routes::game::char::char_immortal::char_immortal_handler)
                .service(routes::game::char::char_imprint_level_up::char_imprint_level_up_handler)
                .service(routes::game::char::char_level_up::char_level_up_handler)
                .service(routes::game::char::char_partner_info::char_partner_info_handler)
                .service(routes::game::char::char_partner_reward::char_partner_reward_handler)
                .service(routes::game::char::char_partner_story_reward::char_partner_story_reward_handler)
                .service(routes::game::char::char_scout_info::char_scout_info_handler)
                .service(routes::game::char::char_special_scout_buy::char_special_scout_buy_handler)
                .service(routes::game::char::char_special_scout_reset::char_special_scout_reset_handler)
                .service(routes::game::clear::clear_package_reward::clear_package_reward_handler)
                .service(routes::game::client::client_custom_log::client_custom_log_handler)
                .service(routes::game::community::community_reward::community_reward_handler)
                .service(routes::game::community::community_reward_info::community_reward_info_handler)
                .service(routes::game::cooking::cooking::cooking_handler)
                .service(routes::game::cooking::cooking_research::cooking_research_handler)
                .service(routes::game::costume::costume_all_rounder_upgrade::costume_all_rounder_upgrade_handler)
                .service(routes::game::costume::costume_clear::costume_clear_handler)
                .service(routes::game::costume::costume_info::costume_info_handler)
                .service(routes::game::costume::costume_node_activation::costume_node_activation_handler)
                .service(routes::game::costume::costume_potential_connect::costume_potential_connect_handler)
                .service(routes::game::costume::costume_upgrade::costume_upgrade_handler)
                .service(routes::game::costume::costume_use::costume_use_handler)
                .service(routes::game::dating::dating_episode_clear::dating_episode_clear_handler)
                .service(routes::game::dating::dating_info::dating_info_handler)
                .service(routes::game::dating::dating_message_update::dating_message_update_handler)
                .service(routes::game::deck::deck_char_auto_revive::deck_char_auto_revive_handler)
                .service(routes::game::deck::deck_costume_setting_info::deck_costume_setting_info_handler)
                .service(routes::game::deck::deck_costume_setting_save::deck_costume_setting_save_handler)
                .service(routes::game::deck::deck_info::deck_info_handler)
                .service(routes::game::deck::deck_save::deck_save_handler)
                .service(routes::game::dispatch::dispatch_info::dispatch_info_handler)
                .service(routes::game::dispatch::dispatch_reward::dispatch_reward_handler)
                .service(routes::game::eat::eat_food::eat_food_handler)
                .service(routes::game::eat::eat_food_auto::eat_food_auto_handler)
                .service(routes::game::equip::equip_add_slot::equip_add_slot_handler)
                .service(routes::game::equip::equip_batch_use::equip_batch_use_handler)
                .service(routes::game::equip::equip_break::equip_break_handler)
                .service(routes::game::equip::equip_change::equip_change_handler)
                .service(routes::game::equip::equip_clear::equip_clear_handler)
                .service(routes::game::equip::equip_from_making_to_break::equip_from_making_to_break_handler)
                .service(routes::game::equip::equip_from_making_to_upgrade::equip_from_making_to_upgrade_handler)
                .service(routes::game::equip::equip_from_upgrade_to_break::equip_from_upgrade_to_break_handler)
                .service(routes::game::equip::equip_lock::equip_lock_handler)
                .service(routes::game::equip::equip_making::equip_making_handler)
                .service(routes::game::equip::equip_mark_delete::equip_mark_delete_handler)
                .service(routes::game::equip::equip_mark_set::equip_mark_set_handler)
                .service(routes::game::equip::equip_option_re_roll::equip_option_re_roll_handler)
                .service(routes::game::equip::equip_option_re_roll_confirm::equip_option_re_roll_confirm_handler)
                .service(routes::game::equip::equip_preset_info::equip_preset_info_handler)
                .service(routes::game::equip::equip_preset_name_change::equip_preset_name_change_handler)
                .service(routes::game::equip::equip_preset_save::equip_preset_save_handler)
                .service(routes::game::equip::equip_sequence_smelting::equip_sequence_smelting_handler)
                .service(routes::game::equip::equip_sequence_upgrade::equip_sequence_upgrade_handler)
                .service(routes::game::equip::equip_smelting::equip_smelting_handler)
                .service(routes::game::equip::equip_storage_add_slot::equip_storage_add_slot_handler)
                .service(routes::game::equip::equip_storage_info::equip_storage_info_handler)
                .service(routes::game::equip::equip_storage_out::equip_storage_out_handler)
                .service(routes::game::equip::equip_storage_put::equip_storage_put_handler)
                .service(routes::game::equip::equip_upgrade::equip_upgrade_handler)
                .service(routes::game::equip::equip_use::equip_use_handler)
                .service(routes::game::equip::equip_main_opt_change::equip_main_opt_change_handler)
                .service(routes::game::equip::equip_making_to_break_auto::equip_making_to_break_auto_handler)
                .service(routes::game::equip::equip_rank_upgrade_buy::equip_rank_upgrade_buy_handler)
                .service(routes::game::equip::equip_upgrade_to_break_auto::equip_upgrade_to_break_auto_handler)
                .service(routes::game::equips::equips_clear::equips_clear_handler)
                .service(routes::game::equips::equips_use::equips_use_handler)
                .service(routes::game::event::event_exchange_info::event_exchange_info_handler)
                .service(routes::game::event::event_exchange_next_page_open::event_exchange_next_page_open_handler)
                .service(routes::game::event::event_exchange_reward::event_exchange_reward_handler)
                .service(routes::game::event::event_hub_info::event_hub_info_handler)
                .service(routes::game::event::event_reward::event_reward_handler)
                .service(routes::game::event::event_schedule_info::event_schedule_info_handler)
                .service(routes::game::evil::evil_castle_daily_reward::evil_castle_daily_reward_handler)
                .service(routes::game::evil::evil_castle_daily_reward_state::evil_castle_daily_reward_state_handler)
                .service(routes::game::evil::evil_castle_enter::evil_castle_enter_handler)
                .service(routes::game::evil::evil_castle_info::evil_castle_info_handler)
                .service(routes::game::evil::evil_castle_ping::evil_castle_ping_handler)
                .service(routes::game::evil::evil_castle_ranking_info::evil_castle_ranking_info_handler)
                .service(routes::game::evil::evil_castle_reward_info::evil_castle_reward_info_handler)
                .service(routes::game::evil::evil_castle_rogue_like_all_user_score_info::evil_castle_rogue_like_all_user_score_info_handler)
                .service(routes::game::evil::evil_castle_rogue_like_battle_char_change::evil_castle_rogue_like_battle_char_change_handler)
                .service(routes::game::evil::evil_castle_rogue_like_battle_end_preview::evil_castle_rogue_like_battle_end_preview_handler)
                .service(routes::game::evil::evil_castle_rogue_like_battle_skip::evil_castle_rogue_like_battle_skip_handler)
                .service(routes::game::evil::evil_castle_rogue_like_char_revival::evil_castle_rogue_like_char_revival_handler)
                .service(routes::game::evil::evil_castle_rogue_like_costume_upgrade::evil_castle_rogue_like_costume_upgrade_handler)
                .service(routes::game::evil::evil_castle_rogue_like_deck_save::evil_castle_rogue_like_deck_save_handler)
                .service(routes::game::evil::evil_castle_rogue_like_edit_event::evil_castle_rogue_like_edit_event_handler)
                .service(routes::game::evil::evil_castle_rogue_like_enter::evil_castle_rogue_like_enter_handler)
                .service(routes::game::evil::evil_castle_rogue_like_event_choice::evil_castle_rogue_like_event_choice_handler)
                .service(routes::game::evil::evil_castle_rogue_like_event_select::evil_castle_rogue_like_event_select_handler)
                .service(routes::game::evil::evil_castle_rogue_like_give_up::evil_castle_rogue_like_give_up_handler)
                .service(routes::game::evil::evil_castle_rogue_like_give_up_info::evil_castle_rogue_like_give_up_info_handler)
                .service(routes::game::evil::evil_castle_rogue_like_growth::evil_castle_rogue_like_growth_handler)
                .service(routes::game::evil::evil_castle_rogue_like_info::evil_castle_rogue_like_info_handler)
                .service(routes::game::evil::evil_castle_rogue_like_move_floor::evil_castle_rogue_like_move_floor_handler)
                .service(routes::game::evil::evil_castle_rogue_like_quick_battle::evil_castle_rogue_like_quick_battle_handler)
                .service(routes::game::evil::evil_castle_rogue_like_rank_info::evil_castle_rogue_like_rank_info_handler)
                .service(routes::game::evil::evil_castle_rogue_like_relic_mix::evil_castle_rogue_like_relic_mix_handler)
                .service(routes::game::evil::evil_castle_rogue_like_reward_re_roll::evil_castle_rogue_like_reward_re_roll_handler)
                .service(routes::game::evil::evil_castle_rogue_like_room_enter::evil_castle_rogue_like_room_enter_handler)
                .service(routes::game::evil::evil_castle_rogue_like_season_reward::evil_castle_rogue_like_season_reward_handler)
                .service(routes::game::evil::evil_castle_rogue_like_select_reward::evil_castle_rogue_like_select_reward_handler)
                .service(routes::game::evil::evil_castle_rogue_like_shop_buy::evil_castle_rogue_like_shop_buy_handler)
                .service(routes::game::evil::evil_castle_rogue_like_shop_exit::evil_castle_rogue_like_shop_exit_handler)
                .service(routes::game::evil::evil_castle_rogue_like_shop_re_roll::evil_castle_rogue_like_shop_re_roll_handler)
                .service(routes::game::evil::evil_castle_stage_clear_reward::evil_castle_stage_clear_reward_handler)
                .service(routes::game::evil::evil_castle_stage_ranking_info::evil_castle_stage_ranking_info_handler)
                .service(routes::game::evil::evil_castle_tower_info::evil_castle_tower_info_handler)
                .service(routes::game::field::field_deck_save::field_deck_save_handler)
                .service(routes::game::field::field_monster_damage::field_monster_damage_handler)
                .service(routes::game::field::field_monster_event::field_monster_event_handler)
                .service(routes::game::field::field_monster_regen::field_monster_regen_handler)
                .service(routes::game::field::field_monster_reward::field_monster_reward_handler)
                .service(routes::game::field::field_object_info::field_object_info_handler)
                .service(routes::game::field::field_object_position_update::field_object_position_update_handler)
                .service(routes::game::field::field_object_preview::field_object_preview_handler)
                .service(routes::game::field::field_object_research::field_object_research_handler)
                .service(routes::game::field::field_object_respawn::field_object_respawn_handler)
                .service(routes::game::field::field_object_reward_list::field_object_reward_list_handler)
                .service(routes::game::field::field_trap_info::field_trap_info_handler)
                .service(routes::game::friend::friend_accept::friend_accept_handler)
                .service(routes::game::friend::friend_info_list::friend_info_list_handler)
                .service(routes::game::friend::friend_receive_list::friend_receive_list_handler)
                .service(routes::game::friend::friend_recommend::friend_recommend_handler)
                .service(routes::game::friend::friend_refuse::friend_refuse_handler)
                .service(routes::game::friend::friend_remove::friend_remove_handler)
                .service(routes::game::friend::friend_search::friend_search_handler)
                .service(routes::game::friend::friend_send::friend_send_handler)
                .service(routes::game::friend::friend_send_list::friend_send_list_handler)
                .service(routes::game::friend::friend_send_remove::friend_send_remove_handler)
                .service(routes::game::gacha::gacha_buy::gacha_buy_handler)
                .service(routes::game::gacha::gacha_buy_preview::gacha_buy_preview_handler)
                .service(routes::game::gacha::gacha_buy_preview_lock::gacha_buy_preview_lock_handler)
                .service(routes::game::gacha::gacha_info::gacha_info_handler)
                .service(routes::game::gacha::gacha_log::gacha_log_handler)
                .service(routes::game::gacha::gacha_point_exchange::gacha_point_exchange_handler)
                .service(routes::game::gacha::gacha_point_manual_exchange::gacha_point_manual_exchange_handler)
                .service(routes::game::gacha::gacha_selection_save::gacha_selection_save_handler)
                .service(routes::game::guild::guild_accept::guild_accept_handler)
                .service(routes::game::guild::guild_create::guild_create_handler)
                .service(routes::game::guild::guild_delete_cancel::guild_delete_cancel_handler)
                .service(routes::game::guild::guild_info::guild_info_handler)
                .service(routes::game::guild::guild_info_edit::guild_info_edit_handler)
                .service(routes::game::guild::guild_init_info::guild_init_info_handler)
                .service(routes::game::guild::guild_join::guild_join_handler)
                .service(routes::game::guild::guild_join_refuse::guild_join_refuse_handler)
                .service(routes::game::guild::guild_join_send_cancel::guild_join_send_cancel_handler)
                .service(routes::game::guild::guild_join_send_info::guild_join_send_info_handler)
                .service(routes::game::guild::guild_leave::guild_leave_handler)
                .service(routes::game::guild::guild_member_ban::guild_member_ban_handler)
                .service(routes::game::guild::guild_member_role_edit::guild_member_role_edit_handler)
                .service(routes::game::guild::guild_notice_info::guild_notice_info_handler)
                .service(routes::game::guild::guild_notice_update::guild_notice_update_handler)
                .service(routes::game::guild::guild_raid_boss_battle_enter::guild_raid_boss_battle_enter_handler)
                .service(routes::game::guild::guild_raid_boss_battle_history::guild_raid_boss_battle_history_handler)
                .service(routes::game::guild::guild_raid_boss_battle_info::guild_raid_boss_battle_info_handler)
                .service(routes::game::guild::guild_raid_boss_practice_battle_enter::guild_raid_boss_practice_battle_enter_handler)
                .service(routes::game::guild::guild_raid_boss_quick_battle::guild_raid_boss_quick_battle_handler)
                .service(routes::game::guild::guild_raid_deck_info::guild_raid_deck_info_handler)
                .service(routes::game::guild::guild_raid_deck_save::guild_raid_deck_save_handler)
                .service(routes::game::guild::guild_raid_main_info::guild_raid_main_info_handler)
                .service(routes::game::guild::guild_raid_member_play_history_info::guild_raid_member_play_history_info_handler)
                .service(routes::game::guild::guild_raid_member_ranking::guild_raid_member_ranking_handler)
                .service(routes::game::guild::guild_raid_normal_battle_history_info::guild_raid_normal_battle_history_info_handler)
                .service(routes::game::guild::guild_raid_normal_battle_info::guild_raid_normal_battle_info_handler)
                .service(routes::game::guild::guild_raid_preset_delete::guild_raid_preset_delete_handler)
                .service(routes::game::guild::guild_raid_preset_info::guild_raid_preset_info_handler)
                .service(routes::game::guild::guild_raid_preset_info_change::guild_raid_preset_info_change_handler)
                .service(routes::game::guild::guild_raid_preset_save::guild_raid_preset_save_handler)
                .service(routes::game::guild::guild_raid_preset_slot_add::guild_raid_preset_slot_add_handler)
                .service(routes::game::guild::guild_raid_preset_use::guild_raid_preset_use_handler)
                .service(routes::game::guild::guild_raid_season_ranking::guild_raid_season_ranking_handler)
                .service(routes::game::guild::guild_raid_season_reward::guild_raid_season_reward_handler)
                .service(routes::game::guild::guild_recommend::guild_recommend_handler)
                .service(routes::game::guild::guild_search::guild_search_handler)
                .service(routes::game::guild::guild_supporter_add::guild_supporter_add_handler)
                .service(routes::game::guild::guild_supporter_delete::guild_supporter_delete_handler)
                .service(routes::game::guild::guild_supporter_info::guild_supporter_info_handler)
                .service(routes::game::guild::guild_supporter_info_list::guild_supporter_info_list_handler)
                .service(routes::game::guild::guild_update_action_info::guild_update_action_info_handler)
                .service(routes::game::hunt::hunt_dispatch::hunt_dispatch_handler)
                .service(routes::game::hunt::hunt_dispatch_end::hunt_dispatch_end_handler)
                .service(routes::game::hunt::hunt_dispatch_info::hunt_dispatch_info_handler)
                .service(routes::game::hunt::hunt_dispatch_reward_preview::hunt_dispatch_reward_preview_handler)
                .service(routes::game::hunt::hunt_dispatch_start::hunt_dispatch_start_handler)
                .service(routes::game::hunting::hunting_ground_enter::hunting_ground_enter_handler)
                .service(routes::game::id::id_card_preset_delete::id_card_preset_delete_handler)
                .service(routes::game::id::id_card_preset_info::id_card_preset_info_handler)
                .service(routes::game::id::id_card_preset_save::id_card_preset_save_handler)
                .service(routes::game::id::id_card_recovery::id_card_recovery_handler)
                .service(routes::game::id::id_card_save::id_card_save_handler)
                .service(routes::game::id::id_card_shop_buy::id_card_shop_buy_handler)
                .service(routes::game::id::id_card_shop_info::id_card_shop_info_handler)
                .service(routes::game::inn::inn_open::inn_open_handler)
                .service(routes::game::interaction::interaction_trigger::interaction_trigger_handler)
                .service(routes::game::inven::inven_add_slot::inven_add_slot_handler)
                .service(routes::game::item::item_dump::item_dump_handler)
                .service(routes::game::item::item_info::item_info_handler)
                .service(routes::game::item::item_storage_info::item_storage_info_handler)
                .service(routes::game::item::item_storage_out::item_storage_out_handler)
                .service(routes::game::item::item_storage_put::item_storage_put_handler)
                .service(routes::game::item::item_storage_update::item_storage_update_handler)
                .service(routes::game::join::join_user::join_user_handler)
                .service(routes::game::jp::jp_user::jp_user_handler)
                .service(routes::game::jp::jp_user_info::jp_user_info_handler)
                .service(routes::game::leave::leave_user::leave_user_handler)
                .service(routes::game::life::life_cheat_build_complete::life_cheat_build_complete_handler)
                .service(routes::game::life::life_cheat_growth::life_cheat_growth_handler)
                .service(routes::game::life::life_cheat_regen::life_cheat_regen_handler)
                .service(routes::game::life::life_citizen_avatar_save::life_citizen_avatar_save_handler)
                .service(routes::game::life::life_citizen_recruit::life_citizen_recruit_handler)
                .service(routes::game::life::life_cooking::life_cooking_handler)
                .service(routes::game::life::life_crafting::life_crafting_handler)
                .service(routes::game::life::life_eat_food::life_eat_food_handler)
                .service(routes::game::life::life_helper_assign::life_helper_assign_handler)
                .service(routes::game::life::life_helper_fire::life_helper_fire_handler)
                .service(routes::game::life::life_helper_gacha::life_helper_gacha_handler)
                .service(routes::game::life::life_helper_gacha_delete::life_helper_gacha_delete_handler)
                .service(routes::game::life::life_helper_reconnect::life_helper_reconnect_handler)
                .service(routes::game::life::life_helper_recruit::life_helper_recruit_handler)
                .service(routes::game::life::life_helper_rename::life_helper_rename_handler)
                .service(routes::game::life::life_helper_reward::life_helper_reward_handler)
                .service(routes::game::life::life_helper_reward_info::life_helper_reward_info_handler)
                .service(routes::game::life::life_info::life_info_handler)
                .service(routes::game::life::life_seeding::life_seeding_handler)
                .service(routes::game::life::life_shop_buy::life_shop_buy_handler)
                .service(routes::game::life::life_shop_buy_info::life_shop_buy_info_handler)
                .service(routes::game::life::life_shop_sell::life_shop_sell_handler)
                .service(routes::game::life::life_stat_save::life_stat_save_handler)
                .service(routes::game::life::life_tool_upgrade::life_tool_upgrade_handler)
                .service(routes::game::life::life_user_info::life_user_info_handler)
                .service(routes::game::life::life_world_choice::life_world_choice_handler)
                .service(routes::game::life::life_world_chunk_expand::life_world_chunk_expand_handler)
                .service(routes::game::life::life_world_object_build_completed::life_world_object_build_completed_handler)
                .service(routes::game::life::life_world_object_deco_save::life_world_object_deco_save_handler)
                .service(routes::game::life::life_world_object_gathering::life_world_object_gathering_handler)
                .service(routes::game::life::life_world_object_place_save::life_world_object_place_save_handler)
                .service(routes::game::life::life_world_object_position_delta_save::life_world_object_position_delta_save_handler)
                .service(routes::game::life::life_world_object_position_save::life_world_object_position_save_handler)
                .service(routes::game::life::life_world_object_status_save::life_world_object_status_save_handler)
                .service(routes::game::life::life_world_object_unplace_save::life_world_object_unplace_save_handler)
                .service(routes::game::fishing::fishing_bait_use::fishing_bait_use_handler)
                .service(routes::game::fishing::fishing_bite_end::fishing_bite_end_handler)
                .service(routes::game::fishing::fishing_bite_fish_hp_update::fishing_bite_fish_hp_update_handler)
                .service(routes::game::fishing::fishing_bite_fish_stamina_update::fishing_bite_fish_stamina_update_handler)
                .service(routes::game::fishing::fishing_bite_start::fishing_bite_start_handler)
                .service(routes::game::fishing::fishing_bite_start_cheat::fishing_bite_start_cheat_handler)
                .service(routes::game::fishing::fishing_boat_skin_buy::fishing_boat_skin_buy_handler)
                .service(routes::game::fishing::fishing_boat_skin_set::fishing_boat_skin_set_handler)
                .service(routes::game::fishing::fishing_boat_upgrade::fishing_boat_upgrade_handler)
                .service(routes::game::fishing::fishing_casting::fishing_casting_handler)
                .service(routes::game::fishing::fishing_collection_info::fishing_collection_info_handler)
                .service(routes::game::fishing::fishing_fish_auto::fishing_fish_auto_handler)
                .service(routes::game::fishing::fishing_fish_inven_slot_add::fishing_fish_inven_slot_add_handler)
                .service(routes::game::fishing::fishing_fish_lock::fishing_fish_lock_handler)
                .service(routes::game::fishing::fishing_info::fishing_info_handler)
                .service(routes::game::fishing::fishing_item_info::fishing_item_info_handler)
                .service(routes::game::fishing::fishing_map_buy::fishing_map_buy_handler)
                .service(routes::game::fishing::fishing_multi_room_info::fishing_multi_room_info_handler)
                .service(routes::game::fishing::fishing_rod_set::fishing_rod_set_handler)
                .service(routes::game::fishing::fishing_shop_buy::fishing_shop_buy_handler)
                .service(routes::game::fishing::fishing_shop_buy_info::fishing_shop_buy_info_handler)
                .service(routes::game::fishing::fishing_shop_sell::fishing_shop_sell_handler)
                .service(routes::game::fishing::fishing_trap_cumulative_reward::fishing_trap_cumulative_reward_handler)
                .service(routes::game::fishing::fishing_trap_info::fishing_trap_info_handler)
                .service(routes::game::fishing::fishing_user_info::fishing_user_info_handler)
                .service(routes::game::fishing::fishing_voyage_end::fishing_voyage_end_handler)
                .service(routes::game::fishing::fishing_voyage_start::fishing_voyage_start_handler)
                .service(routes::game::colosseum::colosseum_ap_buy::colosseum_ap_buy_handler)
                .service(routes::game::colosseum::colosseum_battle_count_reset::colosseum_battle_count_reset_handler)
                .service(routes::game::colosseum::colosseum_battle_end::colosseum_battle_end_handler)
                .service(routes::game::colosseum::colosseum_battle_history::colosseum_battle_history_handler)
                .service(routes::game::colosseum::colosseum_battle_matching::colosseum_battle_matching_handler)
                .service(routes::game::colosseum::colosseum_battle_replay_info::colosseum_battle_replay_info_handler)
                .service(routes::game::colosseum::colosseum_battle_start::colosseum_battle_start_handler)
                .service(routes::game::colosseum::colosseum_bless_info::colosseum_bless_info_handler)
                .service(routes::game::colosseum::colosseum_bless_save::colosseum_bless_save_handler)
                .service(routes::game::colosseum::colosseum_contents_item_renew::colosseum_contents_item_renew_handler)
                .service(routes::game::colosseum::colosseum_deck_info::colosseum_deck_info_handler)
                .service(routes::game::colosseum::colosseum_deck_save::colosseum_deck_save_handler)
                .service(routes::game::colosseum::colosseum_preset_delete::colosseum_preset_delete_handler)
                .service(routes::game::colosseum::colosseum_preset_info::colosseum_preset_info_handler)
                .service(routes::game::colosseum::colosseum_preset_info_change::colosseum_preset_info_change_handler)
                .service(routes::game::colosseum::colosseum_preset_save::colosseum_preset_save_handler)
                .service(routes::game::colosseum::colosseum_preset_slot_add::colosseum_preset_slot_add_handler)
                .service(routes::game::colosseum::colosseum_preset_use::colosseum_preset_use_handler)
                .service(routes::game::colosseum::colosseum_promotion_reward_info::colosseum_promotion_reward_info_handler)
                .service(routes::game::colosseum::colosseum_rank_detail::colosseum_rank_detail_handler)
                .service(routes::game::colosseum::colosseum_ranking::colosseum_ranking_handler)
                .service(routes::game::colosseum::colosseum_season_reward::colosseum_season_reward_handler)
                .service(routes::game::colosseum::colosseum_user_info::colosseum_user_info_handler)
                .service(routes::game::ib::ib_deck_info::ib_deck_info_handler)
                .service(routes::game::ib::ib_deck_save::ib_deck_save_handler)
                .service(routes::game::ib::ib_dungeon_enter::ib_dungeon_enter_handler)
                .service(routes::game::ib::ib_dungeon_give_up::ib_dungeon_give_up_handler)
                .service(routes::game::ib::ib_item_info::ib_item_info_handler)
                .service(routes::game::ib::ib_item_sell::ib_item_sell_handler)
                .service(routes::game::ib::ib_item_upgrade::ib_item_upgrade_handler)
                .service(routes::game::ib::ib_main_info::ib_main_info_handler)
                .service(routes::game::ib::ib_shop_buy::ib_shop_buy_handler)
                .service(routes::game::ib::ib_shop_info::ib_shop_info_handler)
                .service(routes::game::ib::ib_shop_item_reserve::ib_shop_item_reserve_handler)
                .service(routes::game::ib::ib_shop_refresh::ib_shop_refresh_handler)
                .service(routes::game::ib::ib_stage_end::ib_stage_end_handler)
                .service(routes::game::ib::ib_stage_start::ib_stage_start_handler)
                .service(routes::game::like::like_user::like_user_handler)
                .service(routes::game::logout::logout_user::logout_user_handler)
                .service(routes::game::mail::mail_history_info::mail_history_info_handler)
                .service(routes::game::mail::mail_info::mail_info_handler)
                .service(routes::game::mail::mail_open::mail_open_handler)
                .service(routes::game::mercenary::mercenary_scout::mercenary_scout_handler)
                .service(routes::game::mini::mini_game_action_end::mini_game_action_end_handler)
                .service(routes::game::mini::mini_game_action_info::mini_game_action_info_handler)
                .service(routes::game::mini::mini_game_action_ranking::mini_game_action_ranking_handler)
                .service(routes::game::mini::mini_game_action_start::mini_game_action_start_handler)
                .service(routes::game::mini::mini_game_bingo_info::mini_game_bingo_info_handler)
                .service(routes::game::mini::mini_game_bingo_play::mini_game_bingo_play_handler)
                .service(routes::game::mini::mini_game_board_info::mini_game_board_info_handler)
                .service(routes::game::mini::mini_game_board_play::mini_game_board_play_handler)
                .service(routes::game::mini::mini_game_defense_end::mini_game_defense_end_handler)
                .service(routes::game::mini::mini_game_defense_info::mini_game_defense_info_handler)
                .service(routes::game::mini::mini_game_defense_matching::mini_game_defense_matching_handler)
                .service(routes::game::mini::mini_game_defense_start::mini_game_defense_start_handler)
                .service(routes::game::mini::mini_game_field_end::mini_game_field_end_handler)
                .service(routes::game::mini::mini_game_field_info::mini_game_field_info_handler)
                .service(routes::game::mini::mini_game_field_quick_reward::mini_game_field_quick_reward_handler)
                .service(routes::game::mini::mini_game_field_reward::mini_game_field_reward_handler)
                .service(routes::game::mini::mini_game_field_score::mini_game_field_score_handler)
                .service(routes::game::mini::mini_game_field_start::mini_game_field_start_handler)
                .service(routes::game::mini::mini_game_hub_info::mini_game_hub_info_handler)
                .service(routes::game::mini::mini_game_relay_server_info::mini_game_relay_server_info_handler)
                .service(routes::game::mini::mini_game_rhythm_info::mini_game_rhythm_info_handler)
                .service(routes::game::mini::mini_game_rhythm_play_end::mini_game_rhythm_play_end_handler)
                .service(routes::game::mini::mini_game_rhythm_play_start::mini_game_rhythm_play_start_handler)
                .service(routes::game::mini::mini_game_rhythm_ranking::mini_game_rhythm_ranking_handler)
                .service(routes::game::mini::mini_game_roulette_draw::mini_game_roulette_draw_handler)
                .service(routes::game::mini::mini_game_roulette_info::mini_game_roulette_info_handler)
                .service(routes::game::mini::mini_game_run_end::mini_game_run_end_handler)
                .service(routes::game::mini::mini_game_run_info::mini_game_run_info_handler)
                .service(routes::game::mini::mini_game_run_quick_reward::mini_game_run_quick_reward_handler)
                .service(routes::game::mini::mini_game_run_start::mini_game_run_start_handler)
                .service(routes::game::mini::mini_game_sichuan_end::mini_game_sichuan_end_handler)
                .service(routes::game::mini::mini_game_sichuan_info::mini_game_sichuan_info_handler)
                .service(routes::game::mini::mini_game_sichuan_ranking::mini_game_sichuan_ranking_handler)
                .service(routes::game::mini::mini_game_sichuan_start::mini_game_sichuan_start_handler)
                .service(routes::game::mini::mini_game_survival_char_upgrade::mini_game_survival_char_upgrade_handler)
                .service(routes::game::mini::mini_game_survival_char_upgrade_reset::mini_game_survival_char_upgrade_reset_handler)
                .service(routes::game::mini::mini_game_survival_end::mini_game_survival_end_handler)
                .service(routes::game::mini::mini_game_survival_info::mini_game_survival_info_handler)
                .service(routes::game::mini::mini_game_survival_play::mini_game_survival_play_handler)
                .service(routes::game::mini::mini_game_survival_ranking::mini_game_survival_ranking_handler)
                .service(routes::game::mini::mini_game_survival_skill_select_list::mini_game_survival_skill_select_list_handler)
                .service(routes::game::mini::mini_game_survival_skill_up::mini_game_survival_skill_up_handler)
                .service(routes::game::mini::mini_game_survival_start::mini_game_survival_start_handler)
                .service(routes::game::mini::mini_puzzle_all_open::mini_puzzle_all_open_handler)
                .service(routes::game::mini::mini_puzzle_info::mini_puzzle_info_handler)
                .service(routes::game::mini::mini_puzzle_open::mini_puzzle_open_handler)
                .service(routes::game::mini::mini_puzzle_renew::mini_puzzle_renew_handler)
                .service(routes::game::mini::mini_game_hopscotch_info::mini_game_hopscotch_info_handler)
                .service(routes::game::mini::mini_game_hopscotch_game_start::mini_game_hopscotch_game_start_handler)
                .service(routes::game::mini::mini_game_hopscotch_game_end::mini_game_hopscotch_game_end_handler)
                .service(routes::game::mini::mini_game_hopscotch_ranking_info::mini_game_hopscotch_ranking_info_handler)
                .service(routes::game::mini::mini_game_hopscotch_user_record_info::mini_game_hopscotch_user_record_info_handler)
                .service(routes::game::mini::mini_game_action_user_record_info::mini_game_action_user_record_info_handler)
                .service(routes::game::mini::mini_game_rhythm_user_record_info::mini_game_rhythm_user_record_info_handler)
                .service(routes::game::mini::mini_game_sichuan_user_record_info::mini_game_sichuan_user_record_info_handler)
                .service(routes::game::mini::mini_game_survival_user_record_info::mini_game_survival_user_record_info_handler)
                .service(routes::game::mini::mini_game_user_record_info::mini_game_user_record_info_handler)
                .service(routes::game::mini::mini_game_ranking::mini_game_ranking_handler)
                .service(routes::game::spine_interaction::spine_interaction_achievement_info::spine_interaction_achievement_info_handler)
                .service(routes::game::spine_interaction::spine_interaction_achievement_save::spine_interaction_achievement_save_handler)
                .service(routes::game::spine_interaction::spine_interaction_record_info::spine_interaction_record_info_handler)
                .service(routes::game::spine_interaction::spine_interaction_record_detail_info::spine_interaction_record_detail_info_handler)
                .service(routes::game::spine_interaction::spine_interaction_record_save::spine_interaction_record_save_handler)
                .service(routes::game::spine_interaction::spine_interaction_record_data_update::spine_interaction_record_data_update_handler)
                .service(routes::game::spine_interaction::spine_interaction_record_name_update::spine_interaction_record_name_update_handler)
                .service(routes::game::spine_interaction::spine_interaction_record_delete::spine_interaction_record_delete_handler)
                .service(routes::game::spine_interaction::spine_interaction_reward_info::spine_interaction_reward_info_handler)
                .service(routes::game::spine_interaction::spine_interaction_reward::spine_interaction_reward_handler)
                .service(routes::game::spine_interaction::spine_interaction_record_data::spine_interaction_record_data_handler)
                .service(routes::game::char_vote::char_vote_info::char_vote_info_handler)
                .service(routes::game::char_vote::char_vote_favorite_add::char_vote_favorite_add_handler)
                .service(routes::game::char_vote::char_vote_favorite_delete::char_vote_favorite_delete_handler)
                .service(routes::game::char_vote::char_vote_ranking::char_vote_ranking_handler)
                .service(routes::game::char_vote::char_vote_save::char_vote_save_handler)
                .service(routes::game::char_vote::char_vote_season_ranking::char_vote_season_ranking_handler)
                .service(routes::game::char_vote::char_vote_total_ranking::char_vote_total_ranking_handler)
                .service(routes::game::mission::mission_clear::mission_clear_handler)
                .service(routes::game::mission::mission_section_reward::mission_section_reward_handler)
                .service(routes::game::mission::mission_update::mission_update_handler)
                .service(routes::game::monster::monster_hunt_change_team::monster_hunt_change_team_handler)
                .service(routes::game::monster::monster_hunt_deck_info::monster_hunt_deck_info_handler)
                .service(routes::game::monster::monster_hunt_deck_save::monster_hunt_deck_save_handler)
                .service(routes::game::monster::monster_hunt_preset_delete::monster_hunt_preset_delete_handler)
                .service(routes::game::monster::monster_hunt_preset_info::monster_hunt_preset_info_handler)
                .service(routes::game::monster::monster_hunt_preset_info_change::monster_hunt_preset_info_change_handler)
                .service(routes::game::monster::monster_hunt_preset_save::monster_hunt_preset_save_handler)
                .service(routes::game::monster::monster_hunt_preset_slot_add::monster_hunt_preset_slot_add_handler)
                .service(routes::game::monster::monster_hunt_preset_use::monster_hunt_preset_use_handler)
                .service(routes::game::monster::monster_hunt_quick_battle::monster_hunt_quick_battle_handler)
                .service(routes::game::monster::monster_hunt_rank_info::monster_hunt_rank_info_handler)
                .service(routes::game::monster::monster_hunt_schedule_info::monster_hunt_schedule_info_handler)
                .service(routes::game::monster::monster_hunt_season_reward::monster_hunt_season_reward_handler)
                .service(routes::game::monster::monster_hunt_user_info::monster_hunt_user_info_handler)
                .service(routes::game::my::my_like_info::my_like_info_handler)
                .service(routes::game::my::my_room_expand::my_room_expand_handler)
                .service(routes::game::my::my_room_hide::my_room_hide_handler)
                .service(routes::game::my::my_room_item_info::my_room_item_info_handler)
                .service(routes::game::my::my_room_like::my_room_like_handler)
                .service(routes::game::my::my_room_move::my_room_move_handler)
                .service(routes::game::my::my_room_name_change::my_room_name_change_handler)
                .service(routes::game::my::my_room_primary_change::my_room_primary_change_handler)
                .service(routes::game::my::my_room_save::my_room_save_handler)
                .service(routes::game::my::my_room_search_friend::my_room_search_friend_handler)
                .service(routes::game::my::my_room_search_guild::my_room_search_guild_handler)
                .service(routes::game::my::my_room_search_recommend::my_room_search_recommend_handler)
                .service(routes::game::my::my_room_shop_buy::my_room_shop_buy_handler)
                .service(routes::game::my::my_room_shop_info::my_room_shop_info_handler)
                .service(routes::game::my::my_room_user_info::my_room_user_info_handler)
                .service(routes::game::my::my_room_preset_info::my_room_preset_info_handler)
                .service(routes::game::my::my_room_preset_save::my_room_preset_save_handler)
                .service(routes::game::my::my_room_preset_delete::my_room_preset_delete_handler)
                .service(routes::game::my::my_room_preset_name_change::my_room_preset_name_change_handler)
                .service(routes::game::my::my_room_share_option_update::my_room_share_option_update_handler)
                .service(routes::game::my::my_room_shop_multi_buy::my_room_shop_multi_buy_handler)
                .service(routes::game::avatar::avatar_info::avatar_info_handler)
                .service(routes::game::avatar::avatar_save::avatar_save_handler)
                .service(routes::game::avatar::avatar_shop_buy::avatar_shop_buy_handler)
                .service(routes::game::avatar::avatar_motion_shop_buy::avatar_motion_shop_buy_handler)
                .service(routes::game::avatar::avatar_shop_wish_list_info::avatar_shop_wish_list_info_handler)
                .service(routes::game::avatar::avatar_shop_wish_list_save::avatar_shop_wish_list_save_handler)
                .service(routes::game::friendship::friendship_info::friendship_info_handler)
                .service(routes::game::friendship::friendship_counseling::friendship_counseling_handler)
                .service(routes::game::friendship::friendship_gift::friendship_gift_handler)
                .service(routes::game::friendship::friendship_special_episode_clear::friendship_special_episode_clear_handler)
                .service(routes::game::friendship::friendship_special_episode_info::friendship_special_episode_info_handler)
                .service(routes::game::room_chat::room_chat_block_add::room_chat_block_add_handler)
                .service(routes::game::room_chat::room_chat_block_remove::room_chat_block_remove_handler)
                .service(routes::game::room_chat::room_chat_report::room_chat_report_handler)
                .service(routes::game::room_chat::room_chat_report_and_block_info::room_chat_report_and_block_info_handler)
                .service(routes::game::npc::npc_reputation_info::npc_reputation_info_handler)
                .service(routes::game::npc::npc_reputation_recovery::npc_reputation_recovery_handler)
                .service(routes::game::overwhelm::overwhelm_handler)
                .service(routes::game::pack::pack_buy::pack_buy_handler)
                .service(routes::game::pack::pack_detail::pack_detail_handler)
                .service(routes::game::pack::pack_event_story_clear::pack_event_story_clear_handler)
                .service(routes::game::pack::pack_event_story_replay_clear::pack_event_story_replay_clear_handler)
                .service(routes::game::pack::pack_in_game_info::pack_in_game_info_handler)
                .service(routes::game::pack::pack_info::pack_info_handler)
                .service(routes::game::pack::pack_jam_event::pack_jam_event_handler)
                .service(routes::game::pack::pack_reward_object_count::pack_reward_object_count_handler)
                .service(routes::game::pack::pack_sub_quest_clear_info::pack_sub_quest_clear_info_handler)
                .service(routes::game::pass::pass_buy::pass_buy_handler)
                .service(routes::game::pass::pass_info::pass_info_handler)
                .service(routes::game::pass::pass_reward::pass_reward_handler)
                .service(routes::game::personal::personal_info::personal_info_handler)
                .service(routes::game::ping::ping_check::ping_check_handler)
                .service(routes::game::platform::platform_login::platform_login_handler)
                .service(routes::game::popular::popular_costume_info::popular_costume_info_handler)
                .service(routes::game::popular::popular_equip_info::popular_equip_info_handler)
                .service(routes::game::preset::preset_add_slot::preset_add_slot_handler)
                .service(routes::game::preset::preset_delete::preset_delete_handler)
                .service(routes::game::preset::preset_info::preset_info_handler)
                .service(routes::game::preset::preset_info_change::preset_info_change_handler)
                .service(routes::game::preset::preset_save::preset_save_handler)
                .service(routes::game::preset::preset_use::preset_use_handler)
                .service(routes::game::prestige::prestige_skin_info::prestige_skin_info_handler)
                .service(routes::game::prestige::prestige_skin_set::prestige_skin_set_handler)
                .service(routes::game::pvp::pvp_battle_deck_info::pvp_battle_deck_info_handler)
                .service(routes::game::pvp::pvp_battle_deck_save::pvp_battle_deck_save_handler)
                .service(routes::game::pvp::pvp_battle_end::pvp_battle_end_handler)
                .service(routes::game::pvp::pvp_battle_history::pvp_battle_history_handler)
                .service(routes::game::pvp::pvp_battle_history_deck_info::pvp_battle_history_deck_info_handler)
                .service(routes::game::pvp::pvp_battle_matching::pvp_battle_matching_handler)
                .service(routes::game::pvp::pvp_battle_once_reward_info::pvp_battle_once_reward_info_handler)
                .service(routes::game::pvp::pvp_battle_rank_user_detail::pvp_battle_rank_user_detail_handler)
                .service(routes::game::pvp::pvp_battle_ranking::pvp_battle_ranking_handler)
                .service(routes::game::pvp::pvp_battle_replay_info::pvp_battle_replay_info_handler)
                .service(routes::game::pvp::pvp_battle_reset::pvp_battle_reset_handler)
                .service(routes::game::pvp::pvp_battle_reward::pvp_battle_reward_handler)
                .service(routes::game::pvp::pvp_battle_start::pvp_battle_start_handler)
                .service(routes::game::pvp::pvp_battle_user_info::pvp_battle_user_info_handler)
                .service(routes::game::pvp::pvp_contents_item_renew::pvp_contents_item_renew_handler)
                .service(routes::game::pvp::pvp_season_reward::pvp_season_reward_handler)
                .service(routes::game::quest::quest_accept::quest_accept_handler)
                .service(routes::game::quest::quest_give_up::quest_give_up_handler)
                .service(routes::game::quest::quest_immortal_reset::quest_immortal_reset_handler)
                .service(routes::game::quest::quest_info::quest_info_handler)
                .service(routes::game::quest::quest_max_clear_info::quest_max_clear_info_handler)
                .service(routes::game::quick::quick_battle::quick_battle_handler)
                .service(routes::game::recommend::recommend_deck_info::recommend_deck_info_handler)
                .service(routes::game::recommend::recommend_deck_user_option_save::recommend_deck_user_option_save_handler)
                .service(routes::game::refresh::refresh_token::refresh_token_handler)
                .service(routes::game::report::report_user::report_user_handler)
                .service(routes::game::reputation::reputation_info::reputation_info_handler)
                .service(routes::game::root::root_sort_id_info::root_sort_id_info_handler)
                .service(routes::game::save::save_field_char_control_deck_type::save_field_char_control_deck_type_handler)
                .service(routes::game::season::season_reward_info::season_reward_info_handler)
                .service(routes::game::select::select_platform_other_data::select_platform_other_data_handler)
                .service(routes::game::send::send_log::send_log_handler)
                .service(routes::game::shop::shop_buy::shop_buy_handler)
                .service(routes::game::shop::shop_info::shop_info_handler)
                .service(routes::game::shop::shop_open::shop_open_handler)
                .service(routes::game::shop::shop_sell::shop_sell_handler)
                .service(routes::game::sky::sky_way_enter::sky_way_enter_handler)
                .service(routes::game::sky::sky_way_info::sky_way_info_handler)
                .service(routes::game::sky::sky_way_schedule_info::sky_way_schedule_info_handler)
                .service(routes::game::statue::statue_object_reward::statue_object_reward_handler)
                .service(routes::game::storage::storage_add_slot::storage_add_slot_handler)
                .service(routes::game::supporter::supporter_battle_info::supporter_battle_info_handler)
                .service(routes::game::supporter::supporter_borrow::supporter_borrow_handler)
                .service(routes::game::supporter::supporter_detail::supporter_detail_handler)
                .service(routes::game::supporter::supporter_info::supporter_info_handler)
                .service(routes::game::supporter::supporter_register::supporter_register_handler)
                .service(routes::game::supporter::supporter_remove::supporter_remove_handler)
                .service(routes::game::supporter::supporter_reward::supporter_reward_handler)
                .service(routes::game::supporter::supporter_status::supporter_status_handler)
                .service(routes::game::talent::talent_skill_upgrade::talent_skill_upgrade_handler)
                .service(routes::game::talent::talent_skill_use::talent_skill_use_handler)
                .service(routes::game::talent::talent_slot_save::talent_slot_save_handler)
                .service(routes::game::time::time_pause::time_pause_handler)
                .service(routes::game::total::total_war_battle_end::total_war_battle_end_handler)
                .service(routes::game::total::total_war_battle_start::total_war_battle_start_handler)
                .service(routes::game::total::total_war_contents_item_renew::total_war_contents_item_renew_handler)
                .service(routes::game::total::total_war_deck_info::total_war_deck_info_handler)
                .service(routes::game::total::total_war_deck_preset_info::total_war_deck_preset_info_handler)
                .service(routes::game::total::total_war_deck_preset_save::total_war_deck_preset_save_handler)
                .service(routes::game::total::total_war_deck_preset_slot_add::total_war_deck_preset_slot_add_handler)
                .service(routes::game::total::total_war_deck_save::total_war_deck_save_handler)
                .service(routes::game::total::total_war_info::total_war_info_handler)
                .service(routes::game::total::total_war_preset_delete::total_war_preset_delete_handler)
                .service(routes::game::total::total_war_preset_info_change::total_war_preset_info_change_handler)
                .service(routes::game::total::total_war_reward::total_war_reward_handler)
                .service(routes::game::total::total_war_reward_state::total_war_reward_state_handler)
                .service(routes::game::trap::trap_damage::trap_damage_handler)
                .service(routes::game::tutorial::tutorial_info::tutorial_info_handler)
                .service(routes::game::update::update_user_contents_info_option::update_user_contents_info_option_handler)
                .service(routes::game::use2::use_random_box::use_random_box_handler)
                .service(routes::game::use2::use_resource_item::use_resource_item_handler)
                .service(routes::game::user::user_contents_info::user_contents_info_handler)
                .service(routes::game::user::user_contents_info_option::user_contents_info_option_handler)
                .service(routes::game::user::user_greeting_change::user_greeting_change_handler)
                .service(routes::game::user::user_level_reward::user_level_reward_handler)
                .service(routes::game::user::user_nickname_change::user_nickname_change_handler)
                .service(routes::game::user::user_portrait_change::user_portrait_change_handler)
                .service(routes::game::user::user_title_change::user_title_change_handler)
                .service(routes::game::waypoint::waypoint_use::waypoint_use_handler)
                .service(routes::game::overwhelm::overwhelm_handler)
                .service(routes::game::chat::chat_setting_update::chat_setting_update_handler)
                .service(routes::game::content::content_open::content_open_handler)
                .service(routes::game::daily_story::daily_story_info::daily_story_info_handler)
                .service(routes::game::daily_story::daily_story_clear::daily_story_clear_handler)
                .service(routes::game::evil::evil_castle_give_up::evil_castle_give_up_handler)
                .service(routes::game::field_event_spawn::field_event_spawn_info::field_event_spawn_info_handler)
                .service(routes::game::field_event_spawn::field_event_spawn_start::field_event_spawn_start_handler)
                .service(routes::game::field_event_spawn::field_event_spawn_reward::field_event_spawn_reward_handler)
                .service(routes::game::fireworks::fireworks_info::fireworks_info_handler)
                .service(routes::game::fireworks::fireworks_reward::fireworks_reward_handler)
                .service(routes::game::cash::cash_bonus_info::cash_bonus_info_handler)
                .service(routes::game::cash::cash_bonus_reward::cash_bonus_reward_handler)
                .service(routes::game::gacha::gacha_multi_buy::gacha_multi_buy_handler)
                .service(routes::game::guild::guild_name_change::guild_name_change_handler)
                .service(routes::game::item::item_lock::item_lock_handler)
                .service(routes::game::master_title::master_title_info::master_title_info_handler)
                .service(routes::game::master_title::master_title_info_update::master_title_info_update_handler)
                .service(routes::game::mini::mini_event_hub_info::mini_event_hub_info_handler)
                .service(routes::game::npc::npc_quiz_info::npc_quiz_info_handler)
                .service(routes::game::npc::npc_quiz_clear::npc_quiz_clear_handler)
                .service(routes::game::square::square_reward_info::square_reward_info_handler)
                .service(routes::game::square::square_reward::square_reward_handler)
                .service(routes::game::stress_cheat::stress_cheat::stress_cheat_handler)
                .service(routes::game::tactics_bingo::tactics_bingo_deck_save::tactics_bingo_deck_save_handler)
                .service(routes::game::tactics_bingo::tactics_bingo_info::tactics_bingo_info_handler)
                .service(routes::game::age_gate::update_age_gate::update_age_gate_handler)
                .service(routes::game::user::user_relay_info_update::user_relay_info_update_handler)
                .service(routes::game::total::total_ranking::total_ranking_handler)
                .default_service(actix_web::web::route().to(routes::default::fallback::fallback_handler))
        };

        info!("Starting server on {}", &GAME_SERVER_ADDRESS);

        HttpServer::new(app_factory)
            .bind((GAME_SERVER_ADDRESS, 8082))? // HTTP
            .bind_rustls_0_22((GAME_SERVER_ADDRESS, 8443), tls_config)? // HTTPS (Rustls 0.23)
            .run()
            .await?;

        Ok(())
    }
}

fn get_data_path() -> anyhow::Result<PathBuf> {
    let base_dir = if let Ok(manifest_dir) = std::env::var("CARGO_MANIFEST_DIR") {
        PathBuf::from(manifest_dir)
    } else {
        let mut current = std::env::current_dir()?;
        loop {
            if current.join("Cargo.toml").exists() {
                break;
            }
            if !current.pop() {
                return Err(anyhow::anyhow!("Could not find project root"));
            }
        }
        current
    };

    let data_path = base_dir.join("data\\tables");

    if !data_path.exists() {
        return Err(anyhow::anyhow!(
            "Data directory not found at: {}\nExpected to find it at project root",
            data_path.display()
        ));
    }

    Ok(data_path)
}
