CREATE TABLE "BattleCharInfo" (
    "Index" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Uid" BIGINT NOT NULL,
    "UniqueIndex" INTEGER,
    "InvenIndex" BIGINT,
    "Id" INTEGER,
    "Hp" BIGINT,
    "Level" INTEGER,
    "CostumeInvenIndex" BIGINT,
    "CostumeId" INTEGER,
    "CostumeLevel" INTEGER,
    "GridIndex" INTEGER,
    "ReserveCostumeId" INTEGER,
    "IsActiveSubSkillUse" INTEGER,
    "BuffPlusStat" TEXT,
    "BuffMultipleStat" TEXT,
    "AttackDamage" BIGINT,
    "BattlePower" INTEGER,
    "TotalWarPlayType" INTEGER,
    "ConnectPotentialCostume" INTEGER,
    "Key" INTEGER NOT NULL,
    "Value" INTEGER NOT NULL,
    "TargetingCount" INTEGER,
    "SupporterOwnerIndex" BIGINT,
    "SupporterSlotIndex" INTEGER,
    "CostumeDesignId" INTEGER
);