CREATE TABLE "UserInfo" (
    "Index" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Uid" BIGINT NOT NULL,
    "OwnerIndex" BIGINT,
    "UserId" TEXT,
    "UserKey" TEXT,
    "LastPlayPackId" INTEGER,
    "InvenSlot" INTEGER,
    "StorageSlot" INTEGER,
    "Gold" BIGINT,
    "FreeJewelry" BIGINT,
    "Jewelry" BIGINT,
    "EquipSlot" INTEGER,
    "Catalyst" BIGINT,
    "Exp" INTEGER,
    "LevelReward" INTEGER,
    "PortraitCostumeId" INTEGER,
    "EquipStorageSlot" INTEGER,
    "PvpTicket" INTEGER,
    "Medal" INTEGER,
    "EvilCastleCoin" INTEGER,
    "UserType" INTEGER,
    "FreeHuntingAp" INTEGER,
    "BonusHuntingAp" INTEGER,
    "PvpTicketStack" INTEGER,
    "Mileage" INTEGER,
    "HopePowder" INTEGER,
    "UnregDate" BIGINT,
    "PurchaseCountInfoIndex" TEXT, -- References PurchaseCountInfo.InvenIndex
    "IsFirstGacha" INTEGER,
    "PresetSlot" INTEGER,
    "OptimizeInfoIndex" TEXT, -- References OptimizeBaseInfo.InvenIndex
    "BlockDate" BIGINT,
    "ReturnStatusEndTime" BIGINT,
    "MyRoomSlot" INTEGER,
    "TotalWarPresetSlot" INTEGER,
    "EventApFree" INTEGER,
    "EventApStack" INTEGER,
    "FreeTorchLightAp" INTEGER,
    "TorchLightAp" INTEGER,
    "JoinTime" BIGINT,
    "NewbiePassStep" INTEGER,
    "BlockReason" INTEGER,
    "RogueLikeAp" INTEGER,
    "RogueLikeApStack" INTEGER,
    "LoginDate" BIGINT,
    "GuildCoin" BIGINT,
    "CafeteriaCoin" BIGINT,
    "DatingApFree" INTEGER,
    "DatingApStack" INTEGER,
    "MiniGameCoin" BIGINT,
    "CanCharAutoRevive" INTEGER,
    "AutoReviveCastingCharInvenIndex" BIGINT,
    "RecommendDeckUserOptionInfoIndex" BIGINT, -- References RecommendDeckUserOptionInfo.InvenIndex
    "MonsterHuntPresetSlot" INTEGER,
    "GuildRaidPresetSlot" INTEGER,
    "MyRoomDecoCoin" BIGINT,
    "PortraitCostumeDesignId" INTEGER
);
