CREATE TABLE "IbShop" (
    "Uid" BIGINT NOT NULL,
    "Slot" INTEGER NOT NULL,
    "Type" INTEGER NOT NULL DEFAULT 0,
    "ItemId" INTEGER NOT NULL DEFAULT 0,
    "Price" INTEGER NOT NULL DEFAULT 0,
    "OriginalPrice" INTEGER NOT NULL DEFAULT 0,
    "IsDiscount" BOOLEAN NOT NULL DEFAULT 0,
    "IsReserved" BOOLEAN NOT NULL DEFAULT 0,
    "IsSoldOut" BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY ("Uid", "Slot")
);
