CREATE TABLE "PvpUserInfo" (
    "Uid" BIGINT PRIMARY KEY,
    "Vp" INTEGER NOT NULL DEFAULT 1000,
    "WinCount" INTEGER NOT NULL DEFAULT 0,
    "LoseCount" INTEGER NOT NULL DEFAULT 0,
    "SeasonAttackWinCount" INTEGER NOT NULL DEFAULT 0,
    "SeasonAttackLoseCount" INTEGER NOT NULL DEFAULT 0,
    "SeasonDefenseWinCount" INTEGER NOT NULL DEFAULT 0,
    "SeasonDefenseLoseCount" INTEGER NOT NULL DEFAULT 0,
    "PrevSeasonAttackWinCount" INTEGER NOT NULL DEFAULT 0,
    "PrevSeasonAttackLoseCount" INTEGER NOT NULL DEFAULT 0,
    "PrevSeasonDefenseWinCount" INTEGER NOT NULL DEFAULT 0,
    "PrevSeasonDefenseLoseCount" INTEGER NOT NULL DEFAULT 0,
    "DeckSeasonAttackWinCount" INTEGER NOT NULL DEFAULT 0,
    "DeckSeasonAttackLoseCount" INTEGER NOT NULL DEFAULT 0,
    "DeckSeasonDefenseWinCount" INTEGER NOT NULL DEFAULT 0,
    "DeckSeasonDefenseLoseCount" INTEGER NOT NULL DEFAULT 0,
    "DeckSeasonAttackResetTime" BIGINT,
    "DeckSeasonDefenseResetTime" BIGINT,
    "Season" INTEGER NOT NULL DEFAULT 1,
    "CurrentBattleEnemyIndex" BIGINT,
    "OnceRewardClaimed" TEXT NOT NULL DEFAULT '',
    "SeasonRewardClaimedSeason" INTEGER NOT NULL DEFAULT 0
);
