// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PvpBattleDbInfo {
    #[prost(int32, optional, tag = "1")]
    pub vp: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub rank: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub win_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub lose_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub portrait_costume_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "6")]
    pub deck_info: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "7")]
    pub reward_flag: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PvpBattleRankDetailInfo {
    #[prost(int64, optional, tag = "1")]
    pub owner_index: ::core::option::Option<i64>,
    #[prost(int32, optional, tag = "2")]
    pub vp: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub rank: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub win_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub lose_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub portrait_costume_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "7")]
    pub deck_info: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PvpBattleUserInfo {
    #[prost(int64, optional, tag = "1")]
    pub owner_index: ::core::option::Option<i64>,
    #[prost(int32, optional, tag = "2")]
    pub vp: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub rank: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub win_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub lose_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub portrait_costume_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "7")]
    pub deck_info: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CashShopDbInfo {
    #[prost(int32, optional, tag = "1")]
    pub group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub shop_id: ::core::option::Option<i32>,
    #[prost(int64, optional, tag = "3")]
    pub start_time: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "4")]
    pub end_time: ::core::option::Option<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HuntingGroundInfo {
    #[prost(bool, optional, tag = "1")]
    pub is_auto: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "2")]
    pub current_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub highest_id: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcReputationAvgDbInfo {
    #[prost(int32, optional, tag = "1")]
    pub group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub reputation_avg: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcReputationDbInfo {
    #[prost(int32, optional, tag = "1")]
    pub pack_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub npc_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub point: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorldBuffDbInfo {
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(int64, optional, tag = "3")]
    pub remaining_time: ::core::option::Option<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChargeCostRequest {
    #[prost(int32, optional, tag = "1")]
    pub seq: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "2")]
    pub element_type: ::prost::alloc::vec::Vec<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EvilCastleMyRankingInfoRequest {
    #[prost(int32, optional, tag = "1")]
    pub seq: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub pack_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub season_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub stage_index: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImmortalQuestResetRequest {
    #[prost(int32, optional, tag = "1")]
    pub seq: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcReputationInfoRequest {
    #[prost(int32, optional, tag = "1")]
    pub seq: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub group_id: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcReputationRecoveryRequest {
    #[prost(int32, optional, tag = "1")]
    pub seq: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub npc_id: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendLogRequest {
    #[prost(int32, optional, tag = "1")]
    pub seq: ::core::option::Option<i32>,
    #[prost(string, repeated, tag = "2")]
    pub msg: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "send_log_request::LogType", optional, tag = "3")]
    pub log_type: ::core::option::Option<i32>,
}
/// Nested message and enum types in `SendLogRequest`.
pub mod send_log_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "PascalCase")]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum LogType {
        Text = 0,
        Json = 1,
    }
    impl LogType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Text => "TEXT",
                Self::Json => "JSON",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TEXT" => Some(Self::Text),
                "JSON" => Some(Self::Json),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NpcReputationInfoResponse {
    #[prost(message, repeated, tag = "1")]
    pub npc_reputation_info: ::prost::alloc::vec::Vec<NpcReputationDbInfo>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NpcReputationRecoveryResponse {
    #[prost(message, repeated, tag = "1")]
    pub npc_reputation_info: ::prost::alloc::vec::Vec<NpcReputationDbInfo>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendLogResponse {}
