// This file is @generated by prost-build.
/// From: block.db\BlockListTable\UnableChattingTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnableChattingTable {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub unable_chatting_text: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: block.db\BlockListTable\UnableNickNameTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnableNickNameTable {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub unable_nick_name_text: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: block.db\BlockListTable\UnableWildChatTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnableWildChatTable {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub unable_wild_chat_text: ::core::option::Option<::prost::alloc::string::String>,
}
