// This file is @generated by prost-build.
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData1 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData10.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData10 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData10001.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData10001 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData10004.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData10004 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData10006.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData10006 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1001.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData1001 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1002.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData1002 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1003.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData1003 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1004.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData1004 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1005.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData1005 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1006.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData1006 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData1007.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData1007 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData11 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11001.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData11001 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11002.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData11002 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11003.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData11003 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11004.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData11004 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11005.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData11005 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11006.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData11006 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData11007.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData11007 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData12 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12001.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData12001 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12002.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData12002 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12003.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData12003 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12004.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData12004 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12005.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData12005 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12006.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData12006 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData12007.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData12007 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData13.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData13 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData14.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData14 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData15.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData15 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData16.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData16 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData17.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData17 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData18.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData18 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData2 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2001.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData2001 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2002.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData2002 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2003.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData2003 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2004.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData2004 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2005.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData2005 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2006.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData2006 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData2007.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData2007 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData3 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3001.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData3001 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3002.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData3002 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3003.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData3003 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3004.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData3004 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3005.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData3005 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3006.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData3006 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData3007.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData3007 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData4.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData4 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData5.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData5 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData6.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData6 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData7.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData7 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData8.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData8 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
/// From: FieldObjectSceneData.db\FieldObjectSceneDataTable\FieldObjectSceneData9.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldObjectSceneData9 {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub object_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub position_y: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub position_z: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "7")]
    pub scene_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub table_id: ::core::option::Option<i32>,
}
