// This file is @generated by prost-build.
/// From: pack3002.db\BattleTable\BattleDeckTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleDeckTable {
    #[prost(int32, optional, tag = "1")]
    pub battle_clear_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub battle_fail_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "3")]
    pub battle_field_buff: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "4")]
    pub bonus_point_local_text_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "5")]
    pub bonus_point_thumnail_local_text_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "6")]
    pub bonus_point_type: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "7")]
    pub bonus_point_value1: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "8")]
    pub bonus_point_value2: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "9")]
    pub bonus_reward_count: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "10")]
    pub bonus_reward_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "11")]
    pub bonus_reward_type: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "12")]
    pub bonus_score: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "13")]
    pub challenge_type: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "14")]
    pub char_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "15")]
    pub clear_time: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "16")]
    pub clear_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "17")]
    pub clear_type_value: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "18")]
    pub common_sound_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "19")]
    pub costume_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "20")]
    pub costume_id2: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "21")]
    pub costume_use_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "22")]
    pub damage_rate: ::core::option::Option<f64>,
    #[prost(int32, optional, tag = "23")]
    pub death_time_start_turn_pv_e: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "24")]
    pub difficulty_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "25")]
    pub exp: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "26")]
    pub fail_way_point_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "27")]
    pub guide_tutorial_group_id: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "28")]
    pub health_rate: ::core::option::Option<f64>,
    #[prost(int32, optional, tag = "29")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "30")]
    pub level: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, optional, tag = "31")]
    pub map_scene_path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, repeated, packed = "false", tag = "32")]
    pub position: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "33")]
    pub reward_count: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "34")]
    pub reward_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "35")]
    pub reward_supply_type: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "36")]
    pub reward_type: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "37")]
    pub sequence: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "38")]
    pub simple_talk_group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "39")]
    pub solution_tip_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "40")]
    pub tutorial_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "41")]
    pub use_battle_continue: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldActionObjectGroupTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldActionObjectGroupTable {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub mini_map_view_flag: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub regen_sec: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub ui_local_text_id: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldActionObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldActionObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(string, repeated, tag = "3")]
    pub disable_timeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "4")]
    pub field_object_group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub is_enable_timeline: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub is_self_movable: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub map_id: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "9")]
    pub move_speed: ::core::option::Option<f64>,
    #[prost(int32, optional, tag = "10")]
    pub quest_enable_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "11")]
    pub quest_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "12")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "13")]
    pub resource_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "14")]
    pub sample_prefab_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: pack3002.db\FieldTable\FieldBoardObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldBoardObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub map_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub quest_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "6")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "7")]
    pub resource_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub r#type: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldMiniGameObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldMiniGameObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub point: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub point_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub random_group_id: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldMiniGameTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldMiniGameTable {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub map_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub object_group_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "4")]
    pub random_active_count: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "5")]
    pub random_group_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "6")]
    pub start_hp_point: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub time_limit: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldMonsterRegenTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldMonsterRegenTable {
    #[prost(int32, optional, tag = "1")]
    pub gen_distance: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub life_seconds: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub mini_map_view_flag: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub non_gen_distance: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub quest_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub regen_sec: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub regen_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub reset_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "10")]
    pub ui_local_text_id: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldMonsterTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldMonsterTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "2")]
    pub battle_deck_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "3")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "4")]
    pub damaged_effect: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "5")]
    pub direction_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub field_buff_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub field_monster_ai_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub field_point_pos_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub hp: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "10")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "11")]
    pub idle_effect: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "12")]
    pub interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "13")]
    pub interaction_sprite_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "14")]
    pub is_auto_interaction: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "15")]
    pub monster_crash_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "16")]
    pub monster_illust_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "17")]
    pub monster_name_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "18")]
    pub monster_size: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "19")]
    pub monster_talk_story_text_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "20")]
    pub monster_time_line: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, repeated, packed = "false", tag = "21")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "22")]
    pub range_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "23")]
    pub regen_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "24")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "25")]
    pub resource_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "26")]
    pub reward_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "27")]
    pub reward_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "28")]
    pub reward_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "29")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "30")]
    pub use_battle_skip: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldNpcRewardTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldNpcRewardTable {
    #[prost(int32, optional, tag = "1")]
    pub group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub reward_id: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldNpcTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldNpcTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub direction_type: ::core::option::Option<i32>,
    #[prost(string, repeated, tag = "4")]
    pub disable_timeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub face_illust_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "6")]
    pub holding_collection_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "7")]
    pub holding_collection_talk_group_id_list: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "8")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "9")]
    pub interaction_list: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "10")]
    pub interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(string, repeated, tag = "11")]
    pub interaction_sprite_name: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    #[prost(int32, repeated, packed = "false", tag = "12")]
    pub interaction_value: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "13")]
    pub is_enable_timeline: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "14")]
    pub map_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "15")]
    pub npc_default_story_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "16")]
    pub npc_name_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "17")]
    pub pack_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "18")]
    pub quest_enable_type: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "19")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "20")]
    pub range_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "21")]
    pub recovery_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "22")]
    pub reputation_bad_message_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "23")]
    pub reputation_good_message_local_text_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "24")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "25")]
    pub resource_type: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "26")]
    pub talent_charm_char_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "27")]
    pub talent_skill_fail_talk_group_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "28")]
    pub talent_skill_group_list: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "29")]
    pub talent_skill_reward_group_list: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "30")]
    pub talent_skill_success_talk_group_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "31")]
    pub talk_group_id_list: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "32")]
    pub tutorial_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "33")]
    pub tutorial_quest_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "34")]
    pub voice_resource_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: pack3002.db\FieldTable\FieldPointPositionTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldPointPositionTable {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldResearchObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldResearchObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub collection_id: ::core::option::Option<i32>,
    #[prost(string, repeated, tag = "2")]
    pub disable_timeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub holding_collection_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub holding_collection_interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub is_auto_interaction: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub is_display_mini_map: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub is_enable_timeline: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "10")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "11")]
    pub quest_simple_talk_group_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "12")]
    pub quest_timeline: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "14")]
    pub reward_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "15")]
    pub reward_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "16")]
    pub reward_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "17")]
    pub talent_skill_object_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "18")]
    pub r#type: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldRewardObjectGroupTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldRewardObjectGroupTable {
    #[prost(int32, optional, tag = "1")]
    pub buff_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "2")]
    pub buff_id_list: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "3")]
    pub buff_trigger_ratio: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "4")]
    pub casting_sec: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub mini_map_view_flag: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub monster_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub quest_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub reset_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "10")]
    pub reward_group_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "11")]
    pub reward_icon: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "12")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "13")]
    pub ui_local_text_id: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldRewardObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldRewardObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub field_object_group_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "4")]
    pub follow_effect: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "5")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub map_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "7")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub resource_type: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\FieldStatueObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldStatueObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub is_enable_timeline: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub reward_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub reward_local_text_type: ::core::option::Option<i32>,
}
/// From: pack3002.db\FieldTable\ReputationGroupTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReputationGroupTable {
    #[prost(int32, optional, tag = "1")]
    pub down_time: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub good_inn: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub good_price: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub group_name_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub r#type: ::core::option::Option<i32>,
}
/// From: pack3002.db\MapTable\FieldGateTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldGateTable {
    #[prost(int32, optional, tag = "1")]
    pub after_map_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub barricade_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub before_map_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub enable_collection_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub enable_type: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "7")]
    pub field_monster_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "8")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "10")]
    pub position_quest_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "11")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, optional, tag = "12")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "13")]
    pub resource_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "14")]
    pub show_quest_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "15")]
    pub r#type: ::core::option::Option<i32>,
}
/// From: pack3002.db\MapTable\FieldMapRegionObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldMapRegionObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
}
/// From: pack3002.db\MapTable\FieldObjectSwitchTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldObjectSwitchTable {
    #[prost(int32, optional, tag = "1")]
    pub fail_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub field_object_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "4")]
    pub object_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "5")]
    pub order_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub success_local_text_id: ::core::option::Option<i32>,
}
/// From: pack3002.db\MapTable\FieldThrowingTrapGroupTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldThrowingTrapGroupTable {
    #[prost(double, optional, tag = "1")]
    pub decrease_wait_time: ::core::option::Option<f64>,
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub is_random: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub min_wait_time: ::core::option::Option<f64>,
    #[prost(int32, repeated, packed = "false", tag = "5")]
    pub move_direction: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "6")]
    pub move_speed: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub move_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub random_regen_count: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "9")]
    pub regen_object: ::prost::alloc::vec::Vec<i32>,
    #[prost(double, optional, tag = "10")]
    pub start_time: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "11")]
    pub wait_time_start: ::core::option::Option<f64>,
}
/// From: pack3002.db\MapTable\FieldThrowingTrapTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldThrowingTrapTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "4")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "5")]
    pub resource_type: ::core::option::Option<i32>,
}
/// From: pack3002.db\MapTable\FieldTrapTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldTrapTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub default_state: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub field_buff_cool_time: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub field_buff_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub map_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub monster_buff_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "10")]
    pub point_position_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "11")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "12")]
    pub range_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "13")]
    pub regen_sec: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "14")]
    pub reset_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "15")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "16")]
    pub resource_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "17")]
    pub trap_switch_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "18")]
    pub r#type: ::core::option::Option<i32>,
}
/// From: pack3002.db\MapTable\FieldWaypointTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldWaypointTable {
    #[prost(string, repeated, tag = "1")]
    pub disable_timeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub is_enable_timeline: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub is_safe_area: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub map_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "6")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
}
/// From: pack3002.db\MapTable\HuntingGroundTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HuntingGroundTable {
    #[prost(int32, optional, tag = "1")]
    pub boss_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub difficulty: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub map_id: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "5")]
    pub monster_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "6")]
    pub recommend_growth_point: ::core::option::Option<i32>,
}
/// From: pack3002.db\MapTable\MapUiObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MapUiObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub auto_move_inside_npc_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub auto_move_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub available_auto_move: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "4")]
    pub icon_sprite_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "5")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub map_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub quik_auto_move: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "8")]
    pub quik_auto_move_icon_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "9")]
    pub r#type: ::core::option::Option<i32>,
}
/// From: pack3002.db\MapTable\TriggerTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriggerTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "2")]
    pub auto_disabled_sec: ::core::option::Option<f64>,
    #[prost(int32, optional, tag = "3")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(float, repeated, packed = "false", tag = "4")]
    pub delay_time: ::prost::alloc::vec::Vec<f32>,
    #[prost(int32, optional, tag = "5")]
    pub disabled_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub enabled_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub is_auto_interaction: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "10")]
    pub object_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "11")]
    pub object_type: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "12")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, optional, tag = "13")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "14")]
    pub resource_type: ::core::option::Option<i32>,
}
/// From: pack3002.db\QuestTable\FieldObjectAnimationTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldObjectAnimationTable {
    #[prost(string, optional, tag = "1")]
    pub action_animation_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub disable_timeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "4")]
    pub idle_animation_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "5")]
    pub interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub is_enable_timeline: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "7")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
}
/// From: pack3002.db\QuestTable\FieldQuestObjectTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldQuestObjectTable {
    #[prost(int32, optional, tag = "1")]
    pub animator_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub bundle_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub condition_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub direction_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub interaction_local_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub is_auto_interaction: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub is_disable_interaction: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub is_disable_quest_mark: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "10")]
    pub is_display_mini_map: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "11")]
    pub marker_radius: ::core::option::Option<f64>,
    #[prost(int32, repeated, packed = "false", tag = "12")]
    pub quest_range: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "13")]
    pub quest_simple_talk_group_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "14")]
    pub quest_timeline: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "15")]
    pub range_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "16")]
    pub resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "17")]
    pub resource_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "18")]
    pub reward_count: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "19")]
    pub reward_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "20")]
    pub reward_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "21")]
    pub special_animation_state: ::core::option::Option<i32>,
}
/// From: pack3002.db\QuestTable\QuestTitleTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestTitleTable {
    #[prost(int32, optional, tag = "1")]
    pub endquest_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub startquest_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub quest_start_info_quest_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub quest_title_quest_text_id: ::core::option::Option<i32>,
}
/// From: pack3002.db\StoryTable\CinemaTalkTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CinemaTalkTable {
    #[prost(int32, optional, tag = "1")]
    pub accept_timeline: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub background_img_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub bubble_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub dialog_story_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub emotion_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub emotion_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "7")]
    pub face_illust_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, repeated, tag = "9")]
    pub illust_char_animation: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, repeated, packed = "false", tag = "10")]
    pub illust_unique_char_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "11")]
    pub name_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "12")]
    pub pack_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "13")]
    pub pack_index: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "14")]
    pub quest_group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "15")]
    pub quest_group_index: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "16")]
    pub speaker_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "17")]
    pub state: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "18")]
    pub tab_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "19")]
    pub talk_char_index: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "20")]
    pub voice_resource_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: pack3002.db\StoryTable\NPCTalkTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcTalkTable {
    #[prost(int32, optional, tag = "1")]
    pub bubble_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub face_illust_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "5")]
    pub motion: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "6")]
    pub npc_dialog_story_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub npc_name_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "8")]
    pub pack_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub speaker_name: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "10")]
    pub tab_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "11")]
    pub voice_resource_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: pack3002.db\StoryTable\SelectDialogTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelectDialogTable {
    #[prost(int32, repeated, packed = "false", tag = "1")]
    pub dialog_text_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, optional, tag = "2")]
    pub disable_dialog_index: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub id: ::core::option::Option<i32>,
}
/// From: pack3002.db\StoryTable\SimpleTalkTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SimpleTalkTable {
    #[prost(int32, optional, tag = "1")]
    pub dialog_story_text_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub face_illust_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub name_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub pack_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "7")]
    pub pack_index: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub quest_group_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "9")]
    pub voice_resource_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: pack3002.db\StoryTable\VisualNovelDialogTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VisualNovelDialogTable {
    #[prost(string, optional, tag = "1")]
    pub voice_resource_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub bg_illust: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub camera_focus_num: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "4")]
    pub char_action: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, repeated, tag = "5")]
    pub char_face: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, repeated, packed = "false", tag = "6")]
    pub costume_design_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, optional, tag = "7")]
    pub face_illust_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "8")]
    pub group_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "10")]
    pub name_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "11")]
    pub pack_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "12")]
    pub select_dialog_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "13")]
    pub select_num: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "14")]
    pub sound_event_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "15")]
    pub special_event: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "16")]
    pub special_illust: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "17")]
    pub story_text_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "18")]
    pub talk_char_num: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "19")]
    pub r#type: ::core::option::Option<i32>,
}
/// From: pack3002.db\StoryTable\VisualNovelSoundEventTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VisualNovelSoundEventTable {
    #[prost(string, optional, tag = "1")]
    pub ambience_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "2")]
    pub common_sound_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub echo_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "5")]
    pub sound_effect: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: pack3002.db\TextTable\LocalTextTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LocalTextTable {
    #[prost(string, optional, tag = "1")]
    pub date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub text_cn: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub text_en: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub text_jp: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub text_tw: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: pack3002.db\TextTable\QuestTextTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestTextTable {
    #[prost(string, optional, tag = "1")]
    pub date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub text_cn: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub text_en: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub text_jp: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub text_tw: ::core::option::Option<::prost::alloc::string::String>,
}
/// From: pack3002.db\TextTable\StoryTextTable.proto
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoryTextTable {
    #[prost(string, optional, tag = "1")]
    pub date: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "2")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub text_cn: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub text_en: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub text_jp: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub text_tw: ::core::option::Option<::prost::alloc::string::String>,
}
